# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter berlin berlna dubai tundra,$(TARGET_DEVICE)),)

endif
